import os
import torch

DATA_ROOT = "Claude AI Archive"

SENTINEL1_PATH = os.path.join(DATA_ROOT, "1_CLOUD_FREE_DATASET", "1_SENTINEL1", "IMAGE_16_GRID")
SENTINEL2_PATH = os.path.join(DATA_ROOT, "1_CLOUD_FREE_DATASET", "2_SENTINEL2", "IMAGE_16_GRID")
MASK_PATH = os.path.join(DATA_ROOT, "3_TRAINING_MASKS", "MASK_16_GRID")

NUM_PATCHES = 16
PATCH_SIZE = 2816
TRAIN_SPLIT = 0.7
VAL_SPLIT = 0.3

BATCH_SIZE = 2
LEARNING_RATE = 0.0005
NUM_EPOCHS = 50

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

SENTINEL1_BANDS = 2
SENTINEL2_BANDS = 4
MASK_BANDS = 1
